name: Trending News Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Debug check
        run: |
          node -v
          npm list firebase-admin || true

      - name: Run script
        run: node index.js
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
          NVIDIA_API_KEY: ${{ secrets.NVIDIA_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
