name: Trending News Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"   # every hour

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node index.js
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}   ✅
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
